#define		MAX_SAGA_INFO_SIZE					8192 //128000

#define		SAGATEAM_IMPERIAL					1 //e.g. TEAM_RED
#define		SAGATEAM_REBEL						2 //e.g. TEAM_BLUE

#define		SAGA_POINTS_OBJECTIVECOMPLETED		3
#define		SAGA_POINTS_FINALOBJECTIVECOMPLETED	5
#define		SAGA_POINTS_TEAMWONROUND			5
